Explicitly configure htslib --without-libdeflate option as it picks it up when it is installed

diff --git a/.github/workflows/basic.yml b/.github/workflows/basic.yml
--- a/.github/workflows/basic.yml
+++ b/.github/workflows/basic.yml
@@ -32,10 +32,10 @@ jobs:
         os: [ubuntu-22.04]
         type: [basic]
         java: [8,11]
-        include:
-          - os: ubuntu-20.04
-            type: hdfs
-            java: 8
+        #include:
+          #- os: ubuntu-20.04
+          #  type: hdfs
+          #  java: 8
             #- os: ubuntu-18.04
             #  type: hdfs
             #  java: 11
@@ -146,7 +146,11 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         python -m pip install jsondiff
-        make test ARGS=-V
+        make test ARGS=-V || (echo "Tests failed!!" &&
+           cat /home/runner/work/GenomicsDB/GenomicsDB/build/Testing/Temporary/LastTest.log &&
+           echo "SureFire reports..." &&
+           cat /home/runner/work/GenomicsDB/GenomicsDB/build/target/surefire-reports/junitreports/TEST-org.genomicsdb.GenomicsDBLibLoaderTest.xml &&
+           echo "SureFire reports DONE" && exit 1)
 
     - name: Test - Distributed FileSystems
       if: matrix.type == 'hdfs'
